PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0
PRODUCT_VERSION_NAME = tokyo

    CIRCLE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)

CIRCLE_BUILDTYPE ?= UNOFFICIAL
CIRCLE_VERSION_SUFFIX := $(CIRCLE_BUILD_DATE)-$(CIRCLE_BUILDTYPE)$(CIRCLE_EXTRAVERSION)

# Internal version
CIRCLE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CIRCLE_VERSION_SUFFIX)

# Display version
CIRCLE_DISPLAY_VERSION := $(PRODUCT_VERSION_NAME)-$(LINEAGE_VERSION_SUFFIX)
